>D1;SEQ1
<unknown name> - Example DNA sequence 1
ATGCGTACGTAGCTAGCTAGCATCGATCGA---TCGATCGATCGTAGCTA*
>D1;SEQ2
<unknown name> - Example DNA sequence 2
GGTACCTTACGCGATCGATCGTAGCTAGCTAGCTAGCATCGTACGATCGA*
>D1;SEQ3
<unknown name> - Example DNA sequence 3
CTAGCTAGCATGCATGCATGCATGCATGCATG---CATGCATGCATGCAT*
